services:
  - type: web
    name: honeychain-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "bash run.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: HONEYCHAIN_DEMO_MODE
        value: true
      - key: ADMIN_PASSWORD
        value: KvicAdmin@2024
      - key: OFFICER_PASSWORD
        value: KvicOfficer@2024
      - key: LAB_PASSWORD
        value: LabInspector@2024
